/**
 * Mapping of follow-up pack codes to friendly display names
 */
export const FOLLOWUP_PACK_NAMES = {
  'PACK_LE_APPS': 'Law Enforcement Applications',
  'PACK_WITHHOLD_INFO': 'Withholding Information',
  'PACK_DISQUALIFIED': 'Prior Disqualification',
  'PACK_CHEATING': 'Academic Cheating',
  'PACK_DUI': 'DUI / Impaired Driving',
  'PACK_DUI_STOP': 'DUI Stop',
  'PACK_DUI_ARREST': 'DUI Arrest',
  'PACK_LICENSE_SUSPENSION': 'License Suspension',
  'PACK_LICENSE_SUSPENDED': 'Suspended License',
  'PACK_REVOKED_LICENSE': 'Revoked License',
  'PACK_SUSPENDED_LICENSE': 'Suspended License Details',
  'PACK_RECKLESS_DRIVING': 'Reckless Driving',
  'PACK_TRAFFIC': 'Traffic Violations',
  'PACK_TRAFFIC_CITATION': 'Traffic Citation',
  'PACK_CRIMINAL_TRAFFIC': 'Criminal Traffic Offense',
  'PACK_TRAFFIC_ARREST': 'Traffic Arrest',
  'PACK_ROAD_RAGE': 'Road Rage Incident',
  'PACK_OTHER_DRIVING': 'Other Driving Issues',
  'PACK_COLLISION': 'Vehicle Collision',
  'PACK_COLLISION_INJURY': 'Collision with Injury',
  'PACK_ALCOHOL_COLLISION': 'Alcohol-Related Collision',
  'PACK_UNREPORTED_COLLISION': 'Unreported Collision',
  'PACK_HIT_RUN': 'Hit and Run',
  'PACK_HIT_RUN_DAMAGE': 'Hit and Run Damage',
  'PACK_NO_INSURANCE': 'No Insurance',
  'PACK_INSURANCE_REFUSED': 'Insurance Refused',
  'PACK_DRIVE_NO_INSURANCE': 'Driving Without Insurance',
  'PACK_ARREST': 'Arrest History',
  'PACK_CHARGES': 'Criminal Charges',
  'PACK_CRIMINAL_CHARGE': 'Criminal Charge Details',
  'PACK_CONVICTION': 'Criminal Conviction',
  'PACK_DIVERSION': 'Diversion Program',
  'PACK_PROBATION': 'Probation',
  'PACK_INVESTIGATION': 'Criminal Investigation',
  'PACK_POLICE_CALLED': 'Police Called',
  'PACK_FIGHT': 'Physical Altercation',
  'PACK_DOMESTIC_VIOLENCE': 'Domestic Violence',
  'PACK_PROTECTIVE_ORDER': 'Protective Order',
  'PACK_CHILD_CRIME_COMMITTED': 'Crime Against Child',
  'PACK_CHILD_CRIME_ACCUSED': 'Accused of Crime Against Child',
  'PACK_CHILD_PROTECTION': 'Child Protection Services',
  'PACK_SHOPLIFTING': 'Shoplifting',
  'PACK_THEFT_QUESTIONING': 'Theft Questioning',
  'PACK_THEFT': 'Theft',
  'PACK_SIGNATURE_FORGERY': 'Signature Forgery',
  'PACK_HACKING': 'Computer Hacking',
  'PACK_ILLEGAL_DOWNLOADS': 'Illegal Downloads',
  'PACK_STOLEN_PROPERTY': 'Stolen Property',
  'PACK_STOLEN_VEHICLE': 'Stolen Vehicle',
  'PACK_TRESPASSING': 'Trespassing',
  'PACK_PROPERTY_DAMAGE': 'Property Damage',
  'PACK_SERIOUS_INJURY': 'Serious Injury',
  'PACK_HATE_CRIME': 'Hate Crime',
  'PACK_GANG': 'Gang Involvement',
  'PACK_WEAPON_VIOLATION': 'Weapon Violation',
  'PACK_ILLEGAL_WEAPON': 'Illegal Weapon Possession',
  'PACK_CARRY_WEAPON': 'Carrying Weapon',
  'PACK_WARRANT': 'Outstanding Warrant',
  'PACK_FELONY': 'Felony',
  'PACK_FELONY_DETAIL': 'Felony Details',
  'PACK_CONSPIRACY': 'Conspiracy',
  'PACK_PLANNED_CRIME': 'Planned Criminal Activity',
  'PACK_JUVENILE_CRIME': 'Juvenile Crime',
  'PACK_DELETED_SOCIAL_MEDIA': 'Deleted Social Media',
  'PACK_PRANK_CRIME': 'Criminal Prank',
  'PACK_UNCAUGHT_CRIME': 'Unreported Crime',
  'PACK_IRS_INVESTIGATION': 'IRS Investigation',
  'PACK_UNREPORTED_INCOME': 'Unreported Income',
  'PACK_CRIME_FOR_DEBT': 'Crime to Pay Debt',
  'PACK_ILLEGAL_FIREWORKS': 'Illegal Fireworks',
  'PACK_FOREIGN_CRIME': 'Foreign Crime',
  'PACK_POLICE_REPORT': 'Police Report Filed',
  'PACK_LE_INTERVIEW': 'Law Enforcement Interview',
  'PACK_ARRESTABLE_ACTIVITY': 'Arrestable Activity',
  'PACK_CRIMINAL_ASSOCIATES': 'Criminal Associates',
  'PACK_CRIMINAL_ORGANIZATION': 'Criminal Organization',
  'PACK_STOLEN_GOODS': 'Receiving Stolen Goods',
  'PACK_POLICE_BRUTALITY': 'Police Brutality Witness',
  'PACK_DOMESTIC_VICTIM': 'Domestic Violence Victim',
  'PACK_DOMESTIC_ACCUSED': 'Domestic Violence Accusation',
  'PACK_OTHER_CRIMINAL': 'Other Criminal Activity',
  'PACK_EXTREMIST': 'Extremist Organization',
  'PACK_EXTREMIST_DETAIL': 'Extremist Activity Details',
  'PACK_PROSTITUTION': 'Prostitution',
  'PACK_PAID_SEX': 'Paid Sexual Services',
  'PACK_PORNOGRAPHY': 'Pornography Involvement',
  'PACK_HARASSMENT': 'Sexual Harassment',
  'PACK_ASSAULT': 'Sexual Assault',
  'PACK_NON_CONSENT': 'Non-Consensual Activity',
  'PACK_MINOR_CONTACT': 'Inappropriate Contact with Minor',
  'PACK_FINANCIAL': 'Financial Issues',
  'PACK_BANKRUPTCY': 'Bankruptcy',
  'PACK_FORECLOSURE': 'Foreclosure',
  'PACK_REPOSSESSION': 'Repossession',
  'PACK_LAWSUIT': 'Civil Lawsuit',
  'PACK_LATE_PAYMENT': 'Late Payments',
  'PACK_GAMBLING': 'Gambling Issues',
  'PACK_OTHER_FINANCIAL': 'Other Financial Issues',
  'PACK_DRUG_USE': 'Drug Use',
  'PACK_DRUG_SALE': 'Drug Sale/Distribution',
  'PACK_PRESCRIPTION_MISUSE': 'Prescription Drug Misuse',
  'PACK_ALCOHOL_DEPENDENCY': 'Alcohol Dependency',
  'PACK_ALCOHOL_INCIDENT': 'Alcohol-Related Incident',
  'PACK_PROVIDE_ALCOHOL': 'Providing Alcohol to Minors',
  'PACK_MIL_SERVICE': 'Military Service',
  'PACK_MIL_REJECTION': 'Military Rejection',
  'PACK_MIL_DISCHARGE': 'Military Discharge',
  'PACK_MIL_DISCIPLINE': 'Military Discipline',
  'PACK_DISCIPLINE': 'Disciplinary Action',
  'PACK_WORK_DISCIPLINE': 'Work Discipline',
  'PACK_FIRED': 'Termination from Employment',
  'PACK_QUIT_AVOID': 'Quit to Avoid Discipline',
  'PACK_DRUG_TEST_CHEAT': 'Drug Test Cheating',
  'PACK_FALSE_APPLICATION': 'False Application Information',
  'PACK_MISUSE_RESOURCES': 'Misuse of Resources',
  'PACK_UNEMPLOYMENT_FRAUD': 'Unemployment Fraud',
  'PACK_LE_PREV': 'Previous Law Enforcement',
  'PACK_ACCUSED_FORCE': 'Excessive Force Accusation',
  'PACK_GRATUITY': 'Gratuity/Bribery',
  'PACK_FALSIFY_REPORT': 'Falsified Report',
  'PACK_INTERNAL_AFFAIRS': 'Internal Affairs Investigation',
  'PACK_LYING_LE': 'Lying in Law Enforcement',
  'PACK_LE_COMPLAINT': 'Law Enforcement Complaint',
  'PACK_OTHER_PRIOR_LE': 'Other Prior LE Issues',
  'PACK_EMBARRASSMENT': 'Potential Embarrassment',
  'PACK_TATTOO': 'Problematic Tattoos',
  'PACK_SOCIAL_MEDIA': 'Social Media Issues',
  'PACK_DOMESTIC': 'Domestic Issues'
};

export const RESPONSE_TYPE_NAMES = {
  'yes_no': 'Yes / No',
  'text': 'Text',
  'multi_select': 'Multiple Choice',
  'date': 'Date',
  'number': 'Number'
};

export function getFollowupPackDisplay(packCode) {
  if (!packCode) return null;
  const friendlyName = FOLLOWUP_PACK_NAMES[packCode];
  return friendlyName ? `${friendlyName} (${packCode})` : packCode;
}

export function getResponseTypeDisplay(responseType) {
  return RESPONSE_TYPE_NAMES[responseType] || responseType;
}